Разметка внутренних страниц
htmlacademy-adaptive/1934365-cat-energy-25 pull request #3
Opened 2022-04-05 17:43 UTC by NatashaStr

---
:mortar_board: [Разметка внутренних страниц](https://up.htmlacademy.ru/adaptive/25/user/1934365/tasks/3)

:boom: https://htmlacademy-adaptive.github.io/1934365-cat-energy-25/3/

2022-04-07 06:31 UTC, mkolotovich requested changes
Исправьте комментарии

2022-04-07 06:31 UTC, mkolotovich commented on source/form.html
> +            <input type="number" id="age" placeholder="7">
У всех инпутов должен быть атрибут name, чтобы корректно передавать данные на сервер

2022-04-07 06:31 UTC, mkolotovich commented on source/form.html
> +            <input type="checkbox" name="food" id="vitamin">
Здесь лучше задать уникальные имена инпутам, отражающие их подписи, чтобы на сервер уходили данные в корректном виде

2022-04-07 06:31 UTC, mkolotovich commented on source/catalog.html
> +              <button class="button catalog__button" type="button">Заказать</button>
Здесь и в остальных элементах списка кнопку лучше вынести за обертку для удобства построения сетки

2022-04-07 06:31 UTC, mkolotovich commented on source/catalog.html
> +                alt="Cat Energy PRO 500 г">
Здесь и в остальных элементах списка этот текст нужно вынести еще и отдельным элементом, чтобы он был виден всегда, а не только когда изображение не загрузилось

2022-04-07 06:31 UTC, mkolotovich commented on source/form.html
> +            <input type="radio" name="unknown" id="unknown">
чтобы корректно переключались радиобаттоны у них должен быть одинаковое значение атрибута name

2022-04-08 19:35 UTC, NatashaStr commented on source/form.html
> +            <input type="number" id="age" placeholder="7">
исправлено

2022-04-08 19:35 UTC, NatashaStr commented on source/form.html
> +            <input type="checkbox" name="food" id="vitamin">
исправлено

2022-04-08 19:35 UTC, NatashaStr commented on source/catalog.html
> +              <button class="button catalog__button" type="button">Заказать</button>
исправлено

2022-04-08 19:42 UTC, NatashaStr commented on source/catalog.html
> +                alt="Cat Energy PRO 500 г">
исправлено

2022-04-08 19:44 UTC, NatashaStr commented on source/form.html
> +            <input type="radio" name="unknown" id="unknown">
исправлено

2022-04-09 19:35 UTC, merged