Module3 task1
htmlacademy-adaptive/1934365-cat-energy-25 pull request #4
Opened 2022-04-13 18:28 UTC by NatashaStr

2022-04-14 07:35 UTC, mkolotovich requested changes

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +  background-color: rgba(217, 217, 217, 1);
измените цвет на #F2F2F2;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +  background-color: rgba(217, 217, 217, 1);
измените цвет на #EAEAEA

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/main-footer.scss
> +  align-items: center;
задайте background: #F2F2F2;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/contacts.scss
> +
создайте селектор .page__catalog .contacts, page__form .contacts и задайте ему background: #F2F2F2;

2022-04-14 07:35 UTC, mkolotovich commented on source/catalog.html
>  <body class="page__body">
измените класс на page__catalog

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/main-navigation.scss
> +  width: 24px;
задайте background: transparent;

2022-04-14 07:35 UTC, mkolotovich commented on source/form.html
>  <body class="page__body">
измените класс на page__form

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/main-navigation.scss
> +
создайте селектор .main-navigation__item a и задайте ему font-family: 'Oswald'; color: #000000; font-size: 20px;
line-height: 20px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +
создайте селектор .programs__definition и задайте ему color: #444444;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
> +
создайте селектор .advantages__item и задайте ему color: #444444;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +
создайте селектор .example__description и задайте ему color: #444444;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +
создайте селектор .example__number и задайте ему font-family: 'Oswald';
font-size: 24px;
line-height: 24px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +
создайте селектор .example__definition и задайте ему font-size: 12px;
line-height: 100%;
/* or 12px */
color: #444444;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +
создайте селектор .example__description-costs и задайте ему font-family: 'Oswald';
line-height: 20px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +
создайте селектор .example__progress-before, .example__progress-after и задайте ему font-family: 'Oswald';
font-size: 16px;
line-height: 20px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/contacts.scss
> +  color: $black;
задайте color: #111111;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +
создайте селектор .programs__button и задайте ему font-size: 16px;
line-height: 20px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/catalog-container.scss
> +  background-color: rgba(242, 242, 242, 1);
задайте font-size: 16px;
line-height: 20px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/additional-goods.scss
> +
создайте селектор .additional-goods__button и задайте ему font-size: 16px;
line-height: 20px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/form-container.scss
> +
создайте селектор .data__item input, textarea и задайте ему font-family: 'Oswald'; font-size: 16px;
line-height: 18px; color: #444444;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/form-container.scss
> +
создайте селектор .weight-program__item label и задайте ему color: #222222;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/form-container.scss
> +
создайте селектор .master-contacts__title, .comments__title и задайте ему font-size: 24px;
line-height: 26px;
/* or 108% */
color: #000000;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/form-container.scss
> +
создайте селектор .addition__title и задайте ему font-size: 24px;
line-height: 26px;
/* identical to box height, or 108% */
color: #000000;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/form-container.scss
> +
создайте селектор .addition__item label и задайте ему color: #000000;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/form-container.scss
> +
создайте селектор .form__button и задайте ему font-size: 16px;
line-height: 20px;

2022-04-14 07:35 UTC, mkolotovich commented on source/sass/blocks/form-container.scss
> +
создайте селектор .form__description и задайте ему font-family: 'Arial';
font-size: 14px;
line-height: 16px;
/* identical to box height, or 114% */
color: #000000;

2022-04-15 15:13 UTC, NatashaStr commented on source/catalog.html
>  <body class="page__body">
исправлен

2022-04-15 15:13 UTC, NatashaStr commented on source/sass/blocks/contacts.scss
> +
исправлен

2022-04-15 15:13 UTC, NatashaStr commented on source/sass/blocks/main-footer.scss
> +  align-items: center;
исправлен

2022-04-15 15:13 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +  background-color: rgba(217, 217, 217, 1);
исправлен

2022-04-15 15:13 UTC, NatashaStr commented on source/sass/blocks/programs.scss
> +  background-color: rgba(217, 217, 217, 1);
исправлен

2022-04-15 15:15 UTC, NatashaStr commented on source/sass/blocks/main-navigation.scss
> +  width: 24px;
исправлен

2022-04-15 15:16 UTC, NatashaStr commented on source/form.html
>  <body class="page__body">
исправлен

2022-04-15 15:25 UTC, NatashaStr commented on source/sass/blocks/main-navigation.scss
> +
исправлен

2022-04-15 15:28 UTC, NatashaStr commented on source/sass/blocks/programs.scss
> +
исправлен

2022-04-15 15:30 UTC, NatashaStr commented on source/sass/blocks/advantages.scss
> +
исправлен

2022-04-15 15:33 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +
исправлен

2022-04-15 15:35 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +
исправлен

2022-04-15 16:00 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +
исправлен

2022-04-15 16:02 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +
исправлен

2022-04-15 16:04 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +
Исправлен

2022-04-15 16:05 UTC, NatashaStr commented on source/sass/blocks/contacts.scss
> +  color: $black;
исправлен

2022-04-15 16:13 UTC, NatashaStr commented on source/sass/blocks/programs.scss
> +
испарвлен

2022-04-15 16:18 UTC, NatashaStr commented on source/sass/blocks/catalog-container.scss
> +  background-color: rgba(242, 242, 242, 1);
исправлено

2022-04-15 16:24 UTC, NatashaStr commented on source/sass/blocks/additional-goods.scss
> +
исправлен

2022-04-15 16:30 UTC, NatashaStr commented on source/sass/blocks/form-container.scss
> +
исправлен

2022-04-15 16:33 UTC, NatashaStr commented on source/sass/blocks/form-container.scss
> +
исправлен

2022-04-15 16:38 UTC, NatashaStr commented on source/sass/blocks/form-container.scss
> +
исправлен

2022-04-15 16:39 UTC, NatashaStr commented on source/sass/blocks/form-container.scss
> +
исправлен

2022-04-15 16:41 UTC, NatashaStr commented on source/sass/blocks/form-container.scss
> +
исправлен

2022-04-15 16:43 UTC, NatashaStr commented on source/sass/blocks/form-container.scss
> +
исправлен

2022-04-15 16:46 UTC, NatashaStr commented on source/sass/blocks/form-container.scss
> +
исправлен

2022-04-17 07:40 UTC, mkolotovich requested changes
исправьте 2 комментария

2022-04-17 07:40 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +.programs__button {
Измените селектор на .button.programs__button

2022-04-17 07:40 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +  line-height: 16px;
измените значение на 20px;

2022-04-17 07:58 UTC, merged