добавляет адаптив на главную страницу
htmlacademy-adaptive/1934365-cat-energy-25 pull request #5
Opened 2022-04-19 09:03 UTC by NatashaStr

2022-04-19 09:59 UTC, mkolotovich requested changes
исправьте комментарии

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/main-navigation.scss
>    display: block;
задайте     display: none;

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/main-header.scss
>    justify-content: space-between;
задайте    align-items: center;

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/main-header.scss
создайте селектор .main-header__logo-description и задайте ему     margin-left: 56px;

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
> +      <div class="example__container content-center">
уберите класс content-center

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
> +        <iframe class="contacts__map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6037872533268!2d30.320858716070596!3d59.938716481876156!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3
измените значение атрибута width на "100%"

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/main-navigation.scss
создайте селектор .main-navigation для планшета и задайте ему     display: flex;
    align-items: center;

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
> +          <img class="example__image visually-hidden" src="img/main-page/slim-cat.jpg" width="243" height="232"
нет смысла доступно скрывать изображение, для этого есть атрибут alt. здесь уберите класс visually-hidden и сделайте чтобы на планшете отображались два кота

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    background-color: #EAEAEA;
задайте     display: flex; justify-content: space-around;

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/page.scss
> -  margin: 0;
верните это правило

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/main-header.scss
> +    background-color: transparent;
задайте     right: 0;
    left: 0;

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
>        <p class="main-container__description">Занялся собой? Займись котом!</p>
Вот это вложите внутрь блока "programs__intro-wrapper content-center

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
> +      </div>
вот это вырежите и перенесите в блок main-container__wrapper content-center.

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +    position: absolute;
кнопку можно выставить по сетке без позиционирования

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
> +    <div class="main-container__wrapper content-center">
уберите отсюда класс content-center

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
>        <div class="contacts">
этот блок вырежьте и перенесите его на уровень вверх

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
>          <h2 class="example__title">Живой пример</h2>
этот тег вынесите на уровень вверх

2022-04-19 09:59 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    grid-row: 1 / 2;
задайте     width: 1220px;
    margin: auto;

2022-04-19 09:59 UTC, mkolotovich commented on source/index.html
>        </div>
вот этот контент оберните в обертку и задайте ему класс content-center

2022-04-19 14:07 UTC, NatashaStr commented on source/sass/blocks/main-navigation.scss
>    display: block;
исправлено

2022-04-19 14:08 UTC, NatashaStr commented on source/sass/blocks/main-header.scss
>    justify-content: space-between;
исправлено

2022-04-19 14:10 UTC, NatashaStr commented on source/sass/blocks/main-header.scss
исправлено

2022-04-19 14:15 UTC, NatashaStr commented on source/index.html
> +      <div class="example__container content-center">
исправлено

2022-04-19 14:17 UTC, NatashaStr commented on source/index.html
> +        <iframe class="contacts__map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6037872533268!2d30.320858716070596!3d59.938716481876156!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3
исправлено

2022-04-19 14:21 UTC, NatashaStr commented on source/sass/blocks/main-navigation.scss
исправлено

2022-04-19 14:30 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    background-color: #EAEAEA;
исправлено

2022-04-19 14:32 UTC, NatashaStr commented on source/sass/blocks/page.scss
> -  margin: 0;
исправлено

2022-04-19 14:34 UTC, NatashaStr commented on source/sass/blocks/main-header.scss
> +    background-color: transparent;
исправлено

2022-04-19 14:37 UTC, NatashaStr commented on source/index.html
>        <p class="main-container__description">Занялся собой? Займись котом!</p>
исправлено

2022-04-19 14:45 UTC, NatashaStr commented on source/index.html
> +    <div class="main-container__wrapper content-center">
исправлено

2022-04-19 14:53 UTC, NatashaStr commented on source/index.html
> +      </div>
исправлено

2022-04-19 15:51 UTC, NatashaStr commented on source/sass/blocks/programs.scss
> +    position: absolute;
исправлено

2022-04-19 16:07 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    grid-row: 1 / 2;
исправлено

2022-04-20 06:30 UTC, NatashaStr commented on source/index.html
> +          <img class="example__image visually-hidden" src="img/main-page/slim-cat.jpg" width="243" height="232"
исправлено

2022-04-20 06:31 UTC, NatashaStr commented on source/index.html
>          <h2 class="example__title">Живой пример</h2>
исправлено

2022-04-20 06:34 UTC, NatashaStr commented on source/index.html
>        <div class="contacts">
исправлено

2022-04-20 06:43 UTC, NatashaStr commented on source/index.html
>        </div>
исправлено

2022-04-20 08:42 UTC, merged