Декоративные элементы главной страницы
htmlacademy-adaptive/1934365-cat-energy-25 pull request #7
Opened 2022-04-24 16:45 UTC by NatashaStr

2022-04-26 07:30 UTC, mkolotovich requested changes
В этом элементе <img class="main-footer__logo-description logo-text" src="img/main-page/logo-text.jpg" width="" height="24" alt="cat energy"> измените изображение на векторное и задайте ему размеры как на макете. Создайте селектор .advantages__description и задайте ему на планшете font-size: 60px;
line-height: 60px;. Вместо одного элемента <div class="example__progress-bar"></div> для стилизации прогресс бара лучше используйте два, одни для полосы другой для маркера. Для элемента .contacts__address задайте на планшете font-size: 16px;. Этот элемент <p class="example__description-costs">Затраты на питание: 15 000 РУБ.</p> разбейте на 2 элемента.

2022-04-26 07:30 UTC, mkolotovich commented on source/index.html
> +    <nav class="main-navigation main-navigation--opened main-navigation--closed main-navigation--nojs">
удалите класс main-navigation--nojs, по умолчанию кнопка должна отображаться

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/main-navigation.scss
> +    background-color: $black;
Здесь по умолчанию должна быть иконка бургера

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/main-container.scss
> +  background-size: cover;
уберите это свойство и задайте     background-position: center;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/programs.scss
задайте font-size: 14px;
line-height: 18px;     height: 40px;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/programs.scss
>    color: #444444;
задайте     width: 227px;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +  margin-bottom: 23px;
измените на padding-bottom и задайте     border-bottom: solid 1px #D9D9D9;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
> +  padding-left: 100px;
измените значение на 80px

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
>    margin-left: 20px;
измените значение на auto и задайте width: 280px;    margin-right: auto;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +  border-radius: 3px;
задайте     text-transform: uppercase;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +  padding-bottom: 32px;
измените значение на 17px

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +  bottom: -12px;
измените значение на 0px

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/social.scss
> +
Cоздайте селектор .social__link svg и задайте ему fill: #666;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/copyright.scss
> +
создайте селектор .copyright__link svg и задайте ему fill: #666;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/main-header.scss
> +  margin-bottom: 24px;
margin-bottom:0

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/main-navigation.scss
> +// }
расскомментируйте этот код

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/programs.scss
> +      display: none;
уберите это свойство

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
> +    counter-increment: advantages-counter;
задайте font-size: 16px;
line-height: 24px;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/advantages.scss
> +    grid-row: 37px;
удалите эти правила

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    line-height: 60px;
задайте     width: 708px;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    line-height: 24px;
задайте     width: 702px;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    text-align: end;
задайте font-size: 20px;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    padding-right: 40px;
создайте подчеркивание с помощью псевдоэлемента

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/contacts.scss
>    font-weight: 400;
создайте правило для планшета и задайте в нем font-size: 20px;
line-height: 26px;

2022-04-26 07:30 UTC, mkolotovich commented on source/sass/blocks/main-container.scss
>    background-image: linear-gradient(rgba(104, 183, 56, 0.85), rgba(104, 183, 56, 0.85)), url("../img/main-page/cat-background.jpg");
в этом элементе задайте только фоновый цвет и создайте еще один псевдоэлемент для .programs__intro-wrapper и в нём уже задайте фоновое изображение

2022-04-26 16:37 UTC, NatashaStr commented on source/index.html
> +    <nav class="main-navigation main-navigation--opened main-navigation--closed main-navigation--nojs">
исправлено

2022-04-30 09:56 UTC, NatashaStr commented on source/sass/blocks/main-navigation.scss
> +    background-color: $black;
исправлено

2022-04-30 09:59 UTC, NatashaStr commented on source/sass/blocks/main-container.scss
> +  background-size: cover;
исправлено

2022-04-30 10:07 UTC, NatashaStr commented on source/sass/blocks/programs.scss
исправлено, только вместо высоты 40рх, поставила паддинги сверху и снизу по 11рх, чтобы проверку на переполнение пройти

2022-04-30 10:26 UTC, NatashaStr commented on source/sass/blocks/programs.scss
>    color: #444444;
исправлено

2022-04-30 11:07 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    text-align: end;
исправлено

2022-04-30 11:37 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    padding-right: 40px;
исправлено

2022-04-30 12:50 UTC, NatashaStr commented on source/sass/blocks/programs.scss
> +  margin-bottom: 23px;
испарвлено

2022-04-30 12:51 UTC, NatashaStr commented on source/sass/blocks/advantages.scss
> +  padding-left: 100px;
исправлено

2022-04-30 12:58 UTC, NatashaStr commented on source/sass/blocks/example.scss
>    margin-left: 20px;
исправлено

2022-04-30 13:00 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +  border-radius: 3px;
исправлено

2022-04-30 13:01 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +  padding-bottom: 32px;
исправлено

2022-04-30 13:15 UTC, NatashaStr commented on source/sass/blocks/social.scss
> +
исправлено

2022-04-30 13:17 UTC, NatashaStr commented on source/sass/blocks/copyright.scss
> +
исправлено

2022-04-30 13:19 UTC, NatashaStr commented on source/sass/blocks/main-header.scss
> +  margin-bottom: 24px;
исправлено

2022-04-30 16:20 UTC, NatashaStr commented on source/sass/blocks/main-navigation.scss
> +// }
исправлено

2022-04-30 17:00 UTC, NatashaStr commented on source/sass/blocks/programs.scss
> +      display: none;
исправлено

2022-04-30 17:04 UTC, NatashaStr commented on source/sass/blocks/advantages.scss
> +    counter-increment: advantages-counter;
исправлено

2022-04-30 17:08 UTC, NatashaStr commented on source/sass/blocks/advantages.scss
> +    grid-row: 37px;
исправлено. Правило не удалила, исправила на   @media (min-width: $desktop-width) {
    display: flex;
    flex-wrap: wrap;
    column-gap: 0;

2022-04-30 17:09 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    line-height: 60px;
исправлено

2022-04-30 17:10 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    line-height: 24px;
исправлено

2022-04-30 17:13 UTC, NatashaStr commented on source/sass/blocks/contacts.scss
>    font-weight: 400;
исправлено

2022-04-30 17:25 UTC, NatashaStr commented on source/sass/blocks/main-container.scss
>    background-image: linear-gradient(rgba(104, 183, 56, 0.85), rgba(104, 183, 56, 0.85)), url("../img/main-page/cat-background.jpg");
исправлено

2022-05-01 09:14 UTC, mkolotovich requested changes
Исправьте не схлопнтые комментарии с прошлой проверки. Удалите из разметки в элементе `<nav class="main-navigation main-navigation--opened main-navigation--closed">` класс main-navigation--opened.

2022-05-01 09:14 UTC, mkolotovich commented on source/sass/blocks/contacts.scss
> +    font-size: 16px;
задайте     width: 159px;

2022-05-01 09:14 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    align-items: end;
задайте     margin-bottom: 9px;

2022-05-01 09:14 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +    border-bottom: 1px dashed rgba(0, 0, 0, 0.24);
уберите это свойство, это подчеркивание не совпадает с макетом

2022-05-01 09:14 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +      background-color: rgba(0, 0, 0, 0.4);
вместо этого свойства используйте свойство background-image и в нем укажите путь к экспортированной картике подчеркивания из макета

2022-05-01 09:24 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +  padding-bottom: 32px;
исправила - padding-top: 15px;
  padding-bottom: 17px;

2022-05-01 09:26 UTC, NatashaStr commented on source/sass/blocks/main-header.scss
> +  margin-bottom: 24px;
исправлено

2022-05-01 09:32 UTC, NatashaStr commented on source/sass/blocks/contacts.scss
> +    font-size: 16px;
исправлено

2022-05-01 09:38 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    align-items: end;
исправлено

2022-05-01 09:38 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +    border-bottom: 1px dashed rgba(0, 0, 0, 0.24);
исправлено

2022-05-01 09:48 UTC, NatashaStr commented on source/sass/blocks/example.scss
> +      background-color: rgba(0, 0, 0, 0.4);
исправлено

2022-05-01 10:29 UTC, NatashaStr commented on source/sass/blocks/main-container.scss
>    background-image: linear-gradient(rgba(104, 183, 56, 0.85), rgba(104, 183, 56, 0.85)), url("../img/main-page/cat-background.jpg");
Посмотри, пожалуйста, я исправила, но немного по-другому. Но у меня появляется вертикальная полоса, не знаю как её убрать.

2022-05-01 20:49 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +      background-color: rgba(0, 0, 0, 0.4);
в макете, это векторное изображение, а вы экспортировали в растре. Экспортируйте изображение в том же формате, что и в макете

2022-05-01 20:49 UTC, mkolotovich requested changes
Исправьте один не схлопнутый комментарий с прошлой проверки

2022-05-03 06:35 UTC, mkolotovich requested changes
Исправьте комментарий

2022-05-03 06:35 UTC, mkolotovich commented on source/sass/blocks/example.scss
> +      background-image: url("../img/main-page/underline-full.svg");
измените изображениие на underline-dotted.svg

2022-05-03 07:58 UTC, merged