Декоративные элементы внутренних страниц
htmlacademy-adaptive/1934365-cat-energy-25 pull request #8
Opened 2022-05-05 19:33 UTC by NatashaStr

2022-05-06 08:22 UTC, mkolotovich requested changes
Селектору .page__catalog, .page__form задайте overflow-x: hidden;. Селектору .main-header на десктопе задайте     margin-bottom: 78px;. Cелектору .additional-goods__button на планшете задайте     margin-top: 21px;. В элементе <address class="contacts__address">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</address> Санкт-Петербург оберните в отдельный тег.

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/additional-goods.scss
> +      left: -50%;
Измените значение на -80%

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +    padding-top: 28px;
измените значение на 85px

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/additional-goods.scss
> +  }
это правило задайте только для первого элемента .additional-goods__item

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
>      grid-template-columns: 1fr 1fr;
задайте     row-gap: 49px;

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +    margin-bottom: auto;
Картинку лучше спозиционировать абсолютно

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +.catalog__item-wrapper:last-of-type {
измените селектор на .catalog__item:last-of-type

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/additional-goods.scss
> +  margin: 0;
уберите это свойство

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/data.scss
> +    left: -50%;
измените на -100%

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/catalog-container.scss
> +    left: -20%;
измените значение на -100%

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +    left: -20%;
измените на -100%

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +    left: -20%;
задайте -100%

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/weight-program.scss
> +    left: -50%;
задайте -100%

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/comments.scss
>  textarea {
задайте     padding-left: 15px;    padding-top: 9px;

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/weight-program.scss
>      padding-left: 88px;
измените на     padding-left: 27px;

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/form.scss
>      column-gap: 60px;
задайте align-items: center;

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/comments.scss
> +      width: 500%;
задайте     left: -100%;
    width: 500vw;

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/addition.scss
> +      width: 500%;
задайте left: -100%;
    width: 500vw;

2022-05-06 08:22 UTC, mkolotovich commented on source/sass/blocks/addition.scss
> +    height: 26px;
на макете размеры 30 * 30, а на десктопе и планшете 40 * 40

2022-05-07 07:02 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +    padding-top: 28px;
исправлено

2022-05-07 07:09 UTC, NatashaStr commented on source/sass/blocks/additional-goods.scss
> +  }
исправлено

2022-05-07 07:12 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
>      grid-template-columns: 1fr 1fr;
исправлено

2022-05-07 07:24 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +.catalog__item-wrapper:last-of-type {
исправлено

2022-05-07 07:25 UTC, NatashaStr commented on source/sass/blocks/additional-goods.scss
> +  margin: 0;
исправлено

2022-05-07 07:29 UTC, NatashaStr commented on source/sass/blocks/data.scss
> +    left: -50%;
исправлено

2022-05-07 07:30 UTC, NatashaStr commented on source/sass/blocks/catalog-container.scss
> +    left: -20%;
испарвлено

2022-05-07 07:31 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +    left: -20%;
исправлено

2022-05-07 07:32 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +    left: -20%;
исправлено

2022-05-07 07:33 UTC, NatashaStr commented on source/sass/blocks/weight-program.scss
> +    left: -50%;
исправлено

2022-05-07 07:38 UTC, NatashaStr commented on source/sass/blocks/comments.scss
>  textarea {
исправлено

2022-05-07 07:40 UTC, NatashaStr commented on source/sass/blocks/weight-program.scss
>      padding-left: 88px;
исправлено

2022-05-07 07:45 UTC, NatashaStr commented on source/sass/blocks/form.scss
>      column-gap: 60px;
исправлено

2022-05-07 07:47 UTC, NatashaStr commented on source/sass/blocks/comments.scss
> +      width: 500%;
исправлено

2022-05-07 07:48 UTC, NatashaStr commented on source/sass/blocks/addition.scss
> +      width: 500%;
исправлено

2022-05-07 07:53 UTC, NatashaStr commented on source/sass/blocks/addition.scss
> +    height: 26px;
исправлено

2022-05-07 09:54 UTC, NatashaStr commented on source/sass/blocks/additional-goods.scss
> +      left: -50%;
исправлено

2022-05-08 18:26 UTC, mkolotovich requested changes
Селектору .main-navigation__item::before задайте left: -80%;

2022-05-08 18:26 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +
Добавьте закрывающую скобку - }

2022-05-08 18:26 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +  }
создайте правило для десктопа элементу .catalog__item-wrapper и задайте position: static

2022-05-08 18:26 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +  content: "";
зачем здесь и далее свойства content? Это свойство необходимо только для псевдоэлемента, для задания ему содержимого. Здесь оно лишнее. Уберите его.

2022-05-08 18:26 UTC, mkolotovich commented on source/sass/blocks/catalog.scss
> +}
эти правила перенесите в конец файла, чтобы они перебивали правила для мобилы

2022-05-08 18:26 UTC, mkolotovich commented on source/sass/blocks/comments.scss
>    border: 1px solid #E7E7E7;
задайте resize: none;

2022-05-08 18:26 UTC, mkolotovich commented on source/sass/blocks/addition.scss
> +    border: 1px solid #CDCDCD;
задайте box-sizing: border-box;

2022-05-09 05:59 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +
исправлено

2022-05-09 06:04 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +  }
исправлено

2022-05-09 06:06 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +  content: "";
исправлено

2022-05-09 06:08 UTC, NatashaStr commented on source/sass/blocks/catalog.scss
> +}
исправлено

2022-05-09 06:13 UTC, NatashaStr commented on source/sass/blocks/comments.scss
>    border: 1px solid #E7E7E7;
исправлено

2022-05-09 06:15 UTC, NatashaStr commented on source/sass/blocks/addition.scss
> +    border: 1px solid #CDCDCD;
исправлено

2022-05-10 06:49 UTC, mkolotovich requested changes
Селектору .page__body задайте     overflow-x: hidden;

2022-05-10 06:49 UTC, mkolotovich commented on source/sass/global/global.scss
> +  margin: 0 auto;
задайте width: 320px;

2022-05-10 06:49 UTC, mkolotovich commented on source/sass/blocks/main-header.scss
>    margin-bottom: 0;
измените значение на 16px

2022-05-10 06:49 UTC, mkolotovich commented on source/form.html
> +        <svg width="128" height="24" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)" fill="#111"><path d="M1.603 22.051A9.498 9.498 0 0 1 0 16.308V7.795a9.63 9.63 0 0 1 1.502-5.
измените значение атрибута clip-path на "url(#b)"

2022-05-10 08:46 UTC, NatashaStr commented on source/sass/global/global.scss
> +  margin: 0 auto;
Исправила, только ширину задала 280px, а не 320, чтобы контент не прилипал к краям

2022-05-10 09:11 UTC, NatashaStr commented on source/form.html
> +        <svg width="128" height="24" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)" fill="#111"><path d="M1.603 22.051A9.498 9.498 0 0 1 0 16.308V7.795a9.63 9.63 0 0 1 1.502-5.
исправлено

2022-05-10 09:12 UTC, NatashaStr commented on source/sass/blocks/main-header.scss
>    margin-bottom: 0;
исправлено

2022-05-10 11:46 UTC, mkolotovich requested changes
Уберите правило .main-navigation__item:last-child

2022-05-10 13:46 UTC, merged